name: CI

on: push

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, -latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint:prettier --check
      - run: yarn lint
      - run: yarn build
      - run: yarn test
